### ISSUE TITLE
Generate class for custom Input type

### ISSUE THREAD

**Issue by RodolfoSilva** [comigor/artemis#145]
**Bug description**
When I've a mutation with a scalar input, the classes of this input type is not created.
@comigor I'm using hasura, the problem occurs when i try create an insert_* mutation.

```gql
mutation add_product($payload: product_insert_input!) {
    insert_product_one(object: $payload) {
        id
        name
        price
    }
}
```

The artemis is not generating a class for the `product_insert_input`

**Specs**
Artemis version: [e.g. 6.0.3-beta.1]
<details>
<summary>build.yaml:</summary>
  
```yaml
targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - schema.graphql
    builders:
      artemis:
        options:
          fragments_glob: graphql/**.fragment.graphql
          schema_mapping:
            - schema: schema.graphql
              queries_glob: graphql/*.{query,subscription,mutation}.graphql
              output: lib/graphql/graphql_api.dart
              naming_scheme: pathedWithFields
          scalar_mapping:
            - graphql_type: appointment_status
              dart_type: String
            - graphql_type: uuid
              dart_type: String
            - graphql_type: timestamptz
              dart_type: DateTime
            - custom_parser_import: 'package:sw/coercers.dart'
              graphql_type: money
              dart_type: double
            - graphql_type: product_insert_input
              dart_type: dynamic
```
</details>

**Comment by comigor** [comment]
Hey there, @RodolfoSilva!

It's hard to tell without looking at the schema file, but `product_insert_input` is an input object or a scalar?

If it's an input object, you can't have it defined as `scalar_mapping`: Artemis should automatically generate the input class for it. And if it's a scalar, it should work as well ([this test](https://github.com/comigor/artemis/blob/beta/test/query_generator/mutations_and_inputs/custom_scalars_on_input_objects_test.dart) tests that).

**Comment by RodolfoSilva** [comment]
Hey @comigor, `product_insert_input` is an input object. I'll try you suggestion.

**Comment by RodolfoSilva** [comment]
@comigor I've changed my previous comment with the generated code.

**Comment by comigor** [comment]
Uhh, nice, I'll test it here

**Comment by comigor** [comment]
I've found the bug, thinking about a way to fix it!

**Comment by comigor** [comment]
Hey @RodolfoSilva, could you try `6.3.3-beta.1`? (I've just merged and it should be on pub.dev soon).
It should fix your issue, but feel free to reopen this (or any other issue that you find)!

**Comment by RodolfoSilva** [comment]
Hey @comigor, thanks. The problem is partially solved.

If I try to pass an array that contains the input object, it does not generate the class for that input.
Mutation:

```graphql
mutation add_products($payload: [product_insert_input!]!) {
    insert_product(objects: $payload) {
        returning {
          id
          name
          price
        }
    }
}
``` 

<details>
<summary>graphql_api.graphql.dart</summary>

```dart
// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:meta/meta.dart';
import 'package:artemis/artemis.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:equatable/equatable.dart';
import 'package:gql/ast.dart';
import 'package:sw/coercers.dart';
part 'graphql_api.graphql.g.dart';

@JsonSerializable(explicitToJson: true)
class AddProduct$MutationRoot$InsertProduct$Returning with EquatableMixin {
  AddProduct$MutationRoot$InsertProduct$Returning();

  factory AddProduct$MutationRoot$InsertProduct$Returning.fromJson(
          Map<String, dynamic> json) =>
      _$AddProduct$MutationRoot$InsertProduct$ReturningFromJson(json);

  String id;

  String name;

  @JsonKey(
    fromJson: fromGraphQLMoneyToDartdouble,
    toJson: fromDartdoubleToGraphQLMoney,
  )
  double price;

  @override
  List<Object> get props => [id, name, price];
  Map<String, dynamic> toJson() =>
      _$AddProduct$MutationRoot$InsertProduct$ReturningToJson(this);
}

@JsonSerializable(explicitToJson: true)
class AddProduct$MutationRoot$InsertProduct with EquatableMixin {
  AddProduct$MutationRoot$InsertProduct();

  factory AddProduct$MutationRoot$InsertProduct.fromJson(
          Map<String, dynamic> json) =>
      _$AddProduct$MutationRoot$InsertProductFromJson(json);

  List<AddProduct$MutationRoot$InsertProduct$Returning> returning;

  @override
  List<Object> get props => [returning];
  Map<String, dynamic> toJson() =>
      _$AddProduct$MutationRoot$InsertProductToJson(this);
}

@JsonSerializable(explicitToJson: true)
class AddProduct$MutationRoot with EquatableMixin {
  AddProduct$MutationRoot();

  factory AddProduct$MutationRoot.fromJson(Map<String, dynamic> json) =>
      _$AddProduct$MutationRootFromJson(json);

  @JsonKey(name: 'insert_product')
  AddProduct$MutationRoot$InsertProduct insertProduct;

  @override
  List<Object> get props => [insertProduct];
  Map<String, dynamic> toJson() => _$AddProduct$MutationRootToJson(this);
}

@JsonSerializable(explicitToJson: true)
class ProductInsertInput with EquatableMixin {
  ProductInsertInput({this.id, this.name, this.price});

  factory ProductInsertInput.fromJson(Map<String, dynamic> json) =>
      _$ProductInsertInputFromJson(json);

  String id;

  String name;

  @JsonKey(
    fromJson: fromGraphQLMoneyToDartdouble,
    toJson: fromDartdoubleToGraphQLMoney,
  )
  double price;

  @override
  List<Object> get props => [id, name, price];
  Map<String, dynamic> toJson() => _$ProductInsertInputToJson(this);
}

@JsonSerializable(explicitToJson: true)
class AddProductArguments extends JsonSerializable with EquatableMixin {
  AddProductArguments({@required this.payload});

  factory AddProductArguments.fromJson(Map<String, dynamic> json) =>
      _$AddProductArgumentsFromJson(json);

  final List<productInsertInput> payload;

  @override
  List<Object> get props => [payload];
  Map<String, dynamic> toJson() => _$AddProductArgumentsToJson(this);
}

class AddProductMutation
    extends GraphQLQuery<AddProduct$MutationRoot, AddProductArguments> {
  AddProductMutation({this.variables});

  @override
  final DocumentNode document = DocumentNode(definitions: [
    OperationDefinitionNode(
        type: OperationType.mutation,
        name: NameNode(value: 'add_product'),
        variableDefinitions: [
          VariableDefinitionNode(
              variable: VariableNode(name: NameNode(value: 'payload')),
              type: ListTypeNode(
                  type: NamedTypeNode(
                      name: NameNode(value: 'product_insert_input'),
                      isNonNull: true),
                  isNonNull: true),
              defaultValue: DefaultValueNode(value: null),
              directives: [])
        ],
        directives: [],
        selectionSet: SelectionSetNode(selections: [
          FieldNode(
              name: NameNode(value: 'insert_product'),
              alias: null,
              arguments: [
                ArgumentNode(
                    name: NameNode(value: 'objects'),
                    value: VariableNode(name: NameNode(value: 'payload')))
              ],
              directives: [],
              selectionSet: SelectionSetNode(selections: [
                FieldNode(
                    name: NameNode(value: 'returning'),
                    alias: null,
                    arguments: [],
                    directives: [],
                    selectionSet: SelectionSetNode(selections: [
                      FieldNode(
                          name: NameNode(value: 'id'),
                          alias: null,
                          arguments: [],
                          directives: [],
                          selectionSet: null),
                      FieldNode(
                          name: NameNode(value: 'name'),
                          alias: null,
                          arguments: [],
                          directives: [],
                          selectionSet: null),
                      FieldNode(
                          name: NameNode(value: 'price'),
                          alias: null,
                          arguments: [],
                          directives: [],
                          selectionSet: null)
                    ]))
              ]))
        ]))
  ]);

  @override
  final String operationName = 'add_product';

  @override
  final AddProductArguments variables;

  @override
  List<Object> get props => [document, operationName, variables];
  @override
  AddProduct$MutationRoot parse(Map<String, dynamic> json) =>
      AddProduct$MutationRoot.fromJson(json);
}
```
</details>

**Comment by vasilich6107** [comment]
@RodolfoSilva could you check the latest beta?

**Comment by FickleLife** [comment]
@vasilich6107 I have tried both with single input
```gql
mutation MyMutation($object: product_insert_input!) {
  insert_product_one(object: $object) {
    id
  }
}
```
and and array input:
```gql
mutation ProductInsert($object: [product_insert_input!]!) {
  insert_product(objects: $object) {
    affected_rows
  }
}
```

and am getting errors in generated code on `artemis: ^6.4.4-beta.1`

Here's my:
schema: https://paste.ubuntu.com/p/WvXyppMNp6/
Build.yaml
```targets:
  $default:
    sources:
      - lib/**
      - lib/graphql/**
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: lib/graphql/schema/koalaroo.schema.graphql
              queries_glob: lib/graphql/data/**/**.graphql
              output: lib/graphql/graphql_api.dart
          scalar_mapping:
            - graphql_type: timestamptz
              custom_parser_import: 'package:strayan_app/services/artemis_timeconvert.dart'
              dart_type: DateTime
```

**Comment by vasilich6107** [comment]
Attach your schema please

**Comment by RodolfoSilva** [comment]
@vasilich6107 @comigor Working very well. Thanks!!!

**Comment by FickleLife** [comment]
Interesting. Wonder why I am getting issues... @RodolfoSilva are the queries you have stated above generating correctly?

**Comment by FickleLife** [comment]
I think my issue is something else, have opened https://github.com/comigor/artemis/issues/179
